# Generated by Django 4.2.23 on 2025-07-27 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_staff_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchliststockdetail',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
    ]
